version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.25
    commands:
      - CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest

  pre_build:
    commands:
      - cd blog # 以降も blog ディレクトリ内への移動が引き継がれる
      - go mod download # Hugo モジュールをダウンロード
  
  build:
    commands:
      - hugo
      - aws s3 sync --delete public/ s3://${S3_BUCKET_NAME}
  
  post_build:
    commands:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          echo "post build"
        fi
      # TODO: invalidate cloudfront
