baseurl = "https://blog.takamin55.dev/"
DefaultContentLanguage = "ja"
disqusShortname = ""

enableRobotsTXT = true
enableInlineShortcodes = true
timeout = 30000
footnoteReturnLinkContents = "^"

[module]
  [[module.imports]]
    path = "github.com/chipzoller/hugo-clarity"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 10

[permalinks]
post = "post/:slug/"
