version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23.1.0
    commands:
      - cd blog # ここでの移動が各フェーズでも保持される

  pre_build:
    commands:
      - npm ci
  
  build:
    commands:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          npm run build
          aws s3 sync out/ s3://${S3_BUCKET_NAME} --delete
        fi
  
  post_build:
    commands:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          echo "post build"
        fi
      # TODO: invalidate cloudfront

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
