[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -107

#[[social]]
#  name = "github"
#  type = "social"
#  weight = 1
#  url = "https://github.com/a-takamin"

[[social]]
  name = "x"
  weight = 2
  url = "https://x.com/takamin_55"

#[[social]]
#  name = "linkedin"
#  weight = 3
#  url = "https://www.linkedin.com/in/takamin55"
