name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2

        with:
          deno-version: v2.1.4

      - name: ahead-of-time build for tailwind-plugin
        run: deno task build

      - name: upload to deno deploy
        uses: denoland/deployctl@01283bc66613e6b67e329ac8e1eccdcf3c188c93 # 1.13.0
        with:
          project: ${{ secrets.DENO_DEPLOY_PROJECT }}
          entrypoint: "main.ts"
          root: "."