name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install deno
        uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba # v1.1.4
        with:
          deno-version: v1.43.3

      - name: upload to deno deploy
        uses: denoland/deployctl@612f83df2b874c6908d68de5cf3f36a6538fa8f7 # v1.12.0
        with:
          project: ${{ secrets.DENO_DEPLOY_PROJECT }}
          entrypoint: "main.ts"
          root: "."