name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install deno
        uses: denoland/setup-deno@4606d5cc6fb3f673efd4f594850e3f4b3e9d29cd # v2.0.0
        with:
          deno-version: v1.43.3

      - name: ahead-of-time build for tailwind-plugin
        run: deno task build

      - name: upload to deno deploy
        uses: denoland/deployctl@612f83df2b874c6908d68de5cf3f36a6538fa8f7 # v1.12.0
        with:
          project: ${{ secrets.DENO_DEPLOY_PROJECT }}
          entrypoint: "main.ts"
          root: "."